name: GitHub Actions Test

on:
  push:
    branches:
      - develop

env:
  ROLE_TO_ASSUME: arn:aws:iam::767397855647:role/github-actions
  AWS_REGION: ap-northeast-1
  AWS_BUCKET: yoshino-minako-migrations

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  upload-s3-and-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{env.ROLE_TO_ASSUME}}
          role-session-name: github-actions
          aws-region: ${{env.AWS_REGION}}
      # - name: Upload migration files to S3
      #   run: |
      #     aws s3 cp migrations/ s3://${{env.AWS_BUCKET}}/test/ --exclude "*" --include "*.sql" --recursive
      # - name: Remove migration files from S3
      #   run: |
      #     aws s3 rm s3://${{env.AWS_BUCKET}}/test/ --exclude "*" --include "*.sql" --recursive
      # タスク定義のリビジョンを取得
      - name: Get task definition revision
        id: get-task-definition-revision
        run: echo "::set-output name=revision::$(aws ecs list-task-definitions --family-prefix rump-db-migration --sort DESC --query "taskDefinitionArns[0]" --output text --no-paginate)"
      # ECSタスク起動に必要なサブネットとセキュリティグループのIDを取得
      - name: Get subnets ids and security groups ids
        id: get-subnets-and-security-groups
        run: |
          echo "::set-output name=subnets::$(aws ec2 describe-subnets --filter Name=tag:Name,Values=${{ env.SUBNET_NAME }} --query "Subnets[*].[SubnetId]" --output text)"
          echo "::set-output name=security-groups::$(aws ec2 describe-security-groups --filter Name=tag:Name,Values=${{ env.SECURITY_GROUP_NAME }} --query "SecurityGroups[*].[GroupId]" --output text)"
